codecov:
  require_ci_to_pass: no
  branch: master

comment:
  layout: "reach, diff, flags, files"
  behavior: default

coverage:
  range: 50..80
  round: down
  precision: 0

  status:
    project:
      default:
        target: 70
    patch:
      default:
        target: auto
        threshold: 5

fixes:
  - '^\d+\.\d+\.\d+::source'  # move path "X.Y.Z" => "source"
